/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.jakarta.servlet.jsp.jstl.jakarta.servlet.jsp.jstl.api)
    api(libs.org.glassfish.web.jakarta.servlet.jsp.jstl)
    api(libs.org.apache.tomcat.embed.tomcat.embed.jasper)
    runtimeOnly(libs.org.springframework.boot.spring.boot.devtools)
    runtimeOnly(libs.com.mysql.mysql.connector.j)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    compileOnly(libs.jakarta.servlet.jakarta.servlet.api)
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
description = "ToDo"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
